spring:
  application:
    name: "Collectr"
  datasource:
    url: jdbc:postgresql://localhost:5432/collectr
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ""
            clientSecret: ""
          google:
            clientId: ""
            clientSecret: ""